export const AGENT_ERROR = {
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
  INERNAL_SERVER_ERROR: 'INERNAL_SERVER_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AGENT_NOT_AUTHENTICATED: 'AGENT_NOT_AUTHENTICATED',
  FORBIDDEN_TO_ACCESS: 'FORBIDDEN_TO_ACCESS',

  AGENT_NOTFOUND: 'AGENT_NOTFOUND',
  AGENT_ALREADY_EXISTED: 'AGENT_ALREADY_EXISTED',
  RESOURCE_ALREADY_EXISTED: 'RESOURCE_ALREADY_EXISTED',
  PROPERTY_ALREADY_EXISTED: 'PROPERTY_ALREADY_EXISTED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOT_BEFORE: 'NOT_BEFORE',
  MISSING_X_ACCESS_TOKEN: 'MISSING_X_ACCESS_TOKEN',
};
