export const DEFAULT_DATE_FORMAT = 'YYYY-MM-DD';
export const DEFAULT_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';

export const FLIGHT_DATETIME = {
  GoQuo: 'YYYY-MM-DD[T]HH:mm',
  AeroCRS: 'YYYY/MM/DD HH:mm:ss.sss',
  FR24: 'YYYYMMDDHHmm',
  Amadeus: 'DDMMYY HHmm',
  AmadeusShort: 'DDMMYY',
  '1A': 'DDMMYY HHmm',
  IBS: 'YYYY-MM-DD[T]HH:mm:ss[Z]',
  ISA: 'YYYY-MM-DD[T]HH:mm',
  Datacom: 'YYYY-MM-DD[T]HH:mm:ss',
  ITSVietnam: 'YYYY-MM-DD[T]HH:mm:ss',
  Mystifly: 'YYYY-MM-DD[T]HH:mm:ss',
  Letsfly: 'YYYYMMDDHHmm',
  Navitaire: 'YYYY-MM-DD[T]HH:mm:ss',
  PKFare: 'YYYY-MM-DD[T]HH:mm',
  Radixx: 'YYYY-MM-DD[T]HH:mm:ss',
  Sabre: 'YYYY-MM-DD[T]HH:mm:ss',
  Travelport: 'YYYY-MM-DD[T]HH:mm:ss.SSS',
  Via: 'YYYY-MM-DD HH:mm:ss.sss',
  Apollo: 'YYYY-MM-DD HH:mm:ss',
  ClarityTTS: 'YYYY-MM-DD HH:mm:ss',
  SabreGDS: 'YYYY-MM-DD[T]HH:mm:ss',
  Kiwi: 'YYYY-MM-DD[T]HH:mm:ss[Z]',
  AmadeusBI: 'DD-MMM-YY HH:mm',
  Request: 'YYYY-MM-DD',
  FifaEvent: 'YYYY-MM-DD[T]HH:mm',
  NewFifaEvent: 'YYYY-MM-DD HH:mm:ss',
  PG: 'YYYY-MM-DD[T]HH:mm:ss',
  TravelFusion: 'DD/MM/YYYY-HH:mm',
  Vietjet: 'YYYY-MM-DD[T]HH:mm:ss[Z]',
  TravelSkyOTA: 'YYYY-MM-DD[T]HH:mm:ss',
  ISO: 'YYYY-MM-D[T]HH:mm:ss.sss[Z]',
  PSS: 'YYYY-MM-DD[T]HH:mm:ss[Z]',
  SabreNDCv4: 'YYYY-MM-DD[T]HH:mm:ss',
  AeroHub: 'YYYYMMDDHHmm',
  '1A_NATAS': 'DDMMYY HHmm',
};
