export const ERROR = {
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
  INERNAL_SERVER_ERROR: 'INERNAL_SERVER_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',
  FORBIDDEN_TO_ACCESS: 'FORBIDDEN_TO_ACCESS',

  USER_NOTFOUND: 'USER_NOTFOUND',
  USER_ALREADY_EXISTED: 'USER_ALREADY_EXISTED',
  ROLE_ALREADY_EXISTED: 'ROLE_ALREADY_EXISTED',
  PROPERTY_ALREADY_EXISTED: 'PROPERTY_ALREADY_EXISTED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOT_BEFORE: 'NOT_BEFORE',
  MISSING_X_ACCESS_TOKEN: 'MISSING_X_ACCESS_TOKEN',

  METHOD_NOT_IMPLEMENT_YET: 'METHOD_NOT_IMPLEMENT_YET',

  INVALID_CURRENCY_EXCHANGE_PAIR: 'INVALID_CURRENCY_EXCHANGE_PAIR',
  REGION_NOT_FOUND: 'REGION_NOT_FOUND',
  HOTEL_NOT_FOUND: 'HOTEL_NOT_FOUND',
};
