export const SEARCH_ERROR = {
  INVALID_CHECKIN_DATE: 'INVALID_CHECKIN_DATE',
  INVALID_CHECKOUT_DATE: 'INVALID_CHECKOUT_DATE',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_OR_UNSUPPORTED_AIRPORT_CODE: 'INVALID_OR_UNSUPPORTED_AIRPORT_CODE',

  TOUR_NOT_AVAILABLE_WITH_THAT_CONDITIONAL:
    'TOUR_NOT_AVAILABLE_WITH_THAT_CONDITIONAL',
};
