apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: core-vtravel-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-vtravel-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Thay đổi ở đây
