export enum ERoles {
  SUPER_ADMIN = 'super_admin',
  ADMIN_USER = 'admin_user',
  AGENT = 'agent',
  AGENT_INFO = 'agent_info',
  HOTEL_SEARCH_BY_AIRPORT_CODE = 'hotel_search_by_airport_code',
  HOTEL_SEARCH_BY_REGION = 'hotel_search_by_region',
  HOTEL_SEARCH_BY_HOTEL_IDS = 'hotel_search_by_hotel_ids',
  HOTEL_INFO_SEARCH_BY_REGION = 'hotel_info_search_by_region',
  HOTEL_INFO_SEARCH_BY_CITY = 'hotel_info_search_by_city',
  HOTEL_INFO_SEARCH_BY_STREET = 'hotel_info_search_by_street',
  TOUR_SEARCH_BY_AIRPORT_CODE = 'tour_search_by_airport_code',
  TOUR_SEARCH_BY_REGION = 'tour_search_by_region',
  TOUR_SEARCH_BY_HOTEL_IDS = 'tour_search_by_hotel_ids',
  TOUR_INFO_SEARCH_BY_REGION = 'tour_info_search_by_region',
  TOUR_INFO_SEARCH_BY_CITY = 'tour_info_search_by_city',
  TOUR_INFO_SEARCH_BY_STREET = 'tour_info_search_by_street',
}
